# This workflow applies migrations to the staging or production DB.
# Secrets are set in the GH repository environments.

name: deploy-prisma-migrations
run-name: ${{ github.actor }} is deploying migrations to the ${{ github.head_ref || github.ref_name }} DB
on:
  push:
    branches:
      - main
      - production

jobs:
  deploy-migrate:
    runs-on: ubuntu-latest
    environment: Preview
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
